snapshot:
  target:
    entity:
      integration: monoprice
      domain: media_player

restore:
  target:
    entity:
      integration: monoprice
      domain: media_player

set_balance:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 20 inclusive, where 0 is -10(left), 0 is center and 20 is +10 (right).
      required: true
      example: "10"
      default: "0"

set_bass:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: Integer from 0 to 14 inclusive.
      required: true
      example: "10"
      default: "7"
  
set_treble:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: Integer from 0 to 14 inclusive.
      required: true
      example: "10"
      default: "7"

set_all_zones_source:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    source:
      description: integer from 1 to 6 inclusive.
      required: true
      example: "6"
      default: "1"

set_zone_source:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    source:
      description: integer from 1 to 6 inclusive.
      required: true
      example: "6"
      default: "1"


set_volume_level:
  target:
    entity:
      integration: monoprice
      domain: media_player
  fields:
    level:
      description: integer from 0 to 1
      required: true
      example: "0.1"
      default: "0.1"      